version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-ztf"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-s3xfjrxa03x2"
s3_prefix = "aws-ztf"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

